version: '3.1'

services:
  db:
    image: postgres:latest
    privileged: true
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "aggregator_logs"
