# Generated by Django 3.2.12 on 2022-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date_add', models.DateTimeField()),
                ('remote_logname', models.CharField(default='-', max_length=128)),
                ('remote_user', models.CharField(default='-', max_length=128)),
                ('request_line', models.CharField(default='-', max_length=256)),
                ('status', models.CharField(default='-', max_length=4)),
                ('response_bytes', models.CharField(default='-', max_length=128)),
                ('header_referer', models.CharField(default='-', max_length=256)),
                ('header_user_agent', models.CharField(default='-', max_length=256)),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
