# Generated by Django 3.2.12 on 2022-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregatorapp', '0002_auto_20220221_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='header_user_agent',
            field=models.TextField(default='-'),
        ),
    ]
