# Generated by Django 3.2.12 on 2022-02-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregatorapp', '0004_alter_log_request_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_add',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
